### ISSUE TITLE
Transaction type not supported.

### ISSUE THREAD

**Issue by 0x090909** [aj3423/edb#1]
Hey there I would like to use your debugger, but I get this error: 

![Screenshot 2023-11-21 at 19 46 27](https://github.com/aj3423/edb/assets/16927059/2ad6fc78-722f-4cfc-9863-0fdd00d41933)

I think its because the tx is a EIP-1559 transaction

**Comment by aj3423** [comment]
Hi, this error comes from the underlying go-ethereum library, seems it failed to decode the tx, can you provide a sample tx hash?

**Comment by 0x090909** [comment]
@aj3423  Hey there yes! 

this for example 

0x61b15233340de60a0d8963664195c977aca5022c99e95caf69da404a071e8158

It seems only legacy one are supported.

Also I tried to solve the problem by myself by upgrading the library version of go ethereum but then new problem come on top

For example new problems:

The tx.asMessage method is gone in the new version of go ethereum and instead Sender should be used. 

opcode for sha3 is gone as well in the new version

**Comment by 0x090909** [comment]
sorry I forgot to specify network.

its on polygon mainnet

**Comment by aj3423** [comment]
Seems I'm using an old Signer: https://github.com/aj3423/edb/blob/5a4f5d3950e11a9ce8775ea1938be12c8d98818b/eth_client.go#L140

A quickfix would be replacing the `NewEIP155Signer` to `NewLondonSigner`, it works for this transaction:
```
	msg, e := tx.AsMessage(types.NewLondonSigner(big.NewInt(int64(chain_id.Uint64()))), nil)

```

I'll check if this introduces new problem later when I have time.

**Comment by 0x090909** [comment]
This actually may solve it witout upgrading go-ethereum 

Anyway thanks, Ill try

**Comment by 0x090909** [comment]
It works actually thank you, I would like to know if you plan to extend the documentation with more examples, that would be great
